version: '3'
services:
  mysql:
    image: mysql:5.6
    container_name: "mysql.wordpress"
    environment:
    - MYSQL_ROOT_PASSWORD=wordpress
    - MYSQL_DATABASE=wordpress
    - MYSQL_USER=wordpress
    - MYSQL_PASSWORD=wordpress
    networks:
    - userede
    volumes:
    - ./mysql:/var/lib/mysql:z
    ports:
      - "3306:3306"

  php:
    image: wordpress:5.2
    build: .
    container_name: "local.wordpress"
    ports:
    - "80:80"
    links:
    - mysql
    networks:
    - userede
    volumes:
    - ./rede-woocommerce:/var/www/html/wp-content/plugins/rede-woocommerce:z

networks:
  userede:
    driver: bridge
